language: python
python: 2.7
install:
  - pip install tox
  - pip install coveralls
  - pip install codacy-coverage
script:
  - tox
after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
sudo: false